### ISSUE TITLE
Error in ios

### ISSUE THREAD

**Issue by djabif** [stewwan/capacitor-twitter-example#1]
Hi, I'm trying to build this project in ios but I get the following error in xcode. Any idea how to fix it? Thanks

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_TWTRTwitter", referenced from:
      objc-class-ref in Plugin-fa043e0ea75169aabf96fb116196f00ff07bd250f1c06da0ffa457e8c2bf325d.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1
```

**Comment by stewones** [comment]
what's your cocoapod version?

`pod --version`

I went throug this today, fixed by downgrading my local cocoa pod to `1.5.3`
https://1upnote.me/post/2019/02/downgrade-cocoapods/

also you have to

1 - comment out this line on your capacitor app's Podfile, if exists

`install! 'cocoapods', :disable_input_output_paths => true`

2 - sync deps after downgrading cocoapods

- `cd ios/App`
- `pod install`
- `cd ../../`
- `npx cap sync ios`

hope it helps

**Comment by djabif** [comment]
Thanks, it worked :)  
Do you plan to update your plugin to Capacitor 1.0 and  Cocoapods 1.7.0 ?

**Comment by stewones** [comment]
it 's working with capacitor 1.0 already.

for the cocoapods 1.7 Im not sure, need to figure out this bug you filed

**Comment by emmanuel-libertechy** [comment]
I am having the same error with Cocoapods 1.7.1

**Comment by emmanuel-libertechy** [comment]
Hello, Kindly help as I am having the error building on xcode. 
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TWTRTwitter", referenced from:
      objc-class-ref in Plugin-4d0dbad90d6e4f608a50821d1c20f14d644d70fc09d1986c4945ffe9d1c97ca1.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
